from django.urls import path

from apps.intelligence.views import (
    CancelCommercialProposalView,
    CancelProposalView,
    CancelSummaryView,
    CommercialProposalAssumptionsView,
    CommercialProposalDetailView,
    CommercialProposalPdfDownloadView,
    CommercialProposalPricingView,
    CommercialProposalQuestionnaireView,
    CommercialProposalStatusView,
    CommercialProposalTermsView,
    CommercialProposalValidateView,
    ExtractedInsightsListView,
    GenerateCommercialProposalView,
    GenerateProposalView,
    GenerateSummaryView,
    GeneratedProposalDetailView,
    GeneratedSummaryDetailView,
    NewCommercialProposalView,
    NewProposalView,
    PrepareCommercialProposalView,
    ProposalPdfDownloadView,
    ProposalStatusView,
    RegenerateSummaryView,
    SummaryPdfDownloadView,
    SummaryStatusView,
)

urlpatterns = [
    path(
        "documents/<uuid:document_id>/summary/generate/",
        GenerateSummaryView.as_view(),
        name="summary-generate",
    ),
    path(
        "documents/<uuid:document_id>/summary/regenerate/",
        RegenerateSummaryView.as_view(),
        name="summary-regenerate",
    ),
    path(
        "documents/<uuid:document_id>/summary/cancel/",
        CancelSummaryView.as_view(),
        name="summary-cancel",
    ),
    path(
        "documents/<uuid:document_id>/summary/",
        GeneratedSummaryDetailView.as_view(),
        name="summary-detail",
    ),
    path(
        "documents/<uuid:document_id>/summary/download/",
        SummaryPdfDownloadView.as_view(),
        name="summary-pdf-download",
    ),
    path(
        "documents/<uuid:document_id>/summary/status/",
        SummaryStatusView.as_view(),
        name="summary-status",
    ),
    path(
        "documents/<uuid:document_id>/insights/",
        ExtractedInsightsListView.as_view(),
        name="insights-list",
    ),
    path(
        "documents/<uuid:document_id>/proposal/generate/",
        GenerateProposalView.as_view(),
        name="proposal-generate",
    ),
    path(
        "documents/<uuid:document_id>/proposal/new/",
        NewProposalView.as_view(),
        name="proposal-new",
    ),
    path(
        "documents/<uuid:document_id>/proposal/cancel/",
        CancelProposalView.as_view(),
        name="proposal-cancel",
    ),
    path(
        "documents/<uuid:document_id>/proposal/",
        GeneratedProposalDetailView.as_view(),
        name="proposal-detail",
    ),
    path(
        "documents/<uuid:document_id>/proposal/status/",
        ProposalStatusView.as_view(),
        name="proposal-status",
    ),
    path(
        "documents/<uuid:document_id>/proposal/download/",
        ProposalPdfDownloadView.as_view(),
        name="proposal-pdf-download",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/prepare/",
        PrepareCommercialProposalView.as_view(),
        name="commercial-proposal-prepare",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/generate/",
        GenerateCommercialProposalView.as_view(),
        name="commercial-proposal-generate",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/new/",
        NewCommercialProposalView.as_view(),
        name="commercial-proposal-new",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/cancel/",
        CancelCommercialProposalView.as_view(),
        name="commercial-proposal-cancel",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/questionnaire/",
        CommercialProposalQuestionnaireView.as_view(),
        name="commercial-proposal-questionnaire",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/pricing/",
        CommercialProposalPricingView.as_view(),
        name="commercial-proposal-pricing",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/assumptions/",
        CommercialProposalAssumptionsView.as_view(),
        name="commercial-proposal-assumptions",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/terms/",
        CommercialProposalTermsView.as_view(),
        name="commercial-proposal-terms",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/validate/",
        CommercialProposalValidateView.as_view(),
        name="commercial-proposal-validate",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/",
        CommercialProposalDetailView.as_view(),
        name="commercial-proposal-detail",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/status/",
        CommercialProposalStatusView.as_view(),
        name="commercial-proposal-status",
    ),
    path(
        "documents/<uuid:document_id>/commercial-proposal/download/",
        CommercialProposalPdfDownloadView.as_view(),
        name="commercial-proposal-pdf-download",
    ),
]
